### ISSUE TITLE
files aren't namespaced

### ISSUE THREAD

**Issue by EntranceJew** [thebigsleepjoe/TTT-Bots-2#1]
sorry to interrupt, but having all your files outside of a namespaced folder might open it up for collisions with other addons; for example, the file `includes/lib/languages.lua` is pretty generic, same with `autorun/client/debugui.lua` -- and since all addons mount on top of each other, someone could very likely overwrite one or more of your files.

my suggestion would be to minimize your footprint to one very unique autorun filename, and then move all your files into `lua/ttt-bots-2/*`

**Comment by thebigsleepjoe** [comment]
That's a good point. I think I'll do that.

To be honest, I assumed Garry's Mod loaded add-ons into their own namespace by default -- especially considering how large the modding scene for this game is.

**Comment by thebigsleepjoe** [comment]
Thank you for bringing that up. I'm sure that would have become an annoying future problem.

The relevant changes have been made, and the code generally looks cleaner now.
