### ISSUE TITLE
[BUG] Ladders are problematic

### ISSUE THREAD

**Issue by Cynosphere** [thebigsleepjoe/TTT-Bots-2#15]
## Game version/server type
* SERVER TYPE: ALL
* WHICH TTT: TTT/2
* WHAT VERSION OF BOTS: 0.9.1 (12/16/23)

## Describe the bug
- Bots should not attempt to use a ladder if there is already someone else on it to avoid piling up on the ladder
- Assumptions are being made on how to dismount the ladder if the top of it ends with a walkable surface, but does not check if said surface is accessible (screenshot 1 and 2), the top connected node should be used instead.
- Bots try to crouch jump to dismount a ladder when going down (screenshot 3) (may be specific to func_useableladder?)

## Screenshots
![Bot trying to pathfind off a ladder through a wall instead of](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/1606710/6a469f6e-0667-4848-90ec-3383a94e4c44)
![The walkable surface through the wall](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/1606710/ed275b32-dcc7-4a0f-a351-c6e813b9c8b1)
![Bot stuck crouch jumping trying to dismount a ladder](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/1606710/9e7d9ed0-dcea-48d3-8901-b7b0d3812c6f)

## Additional context
Navmesh has manually created ladder nodes (via `navmesh.CreateNavLadder`) as func_useableladder is not recognized by the navigation editor.
[ttt_bb_teenroom_b2.nav.zip](https://github.com/thebigsleepjoe/TTT-Bots-2/files/13698132/ttt_bb_teenroom_b2.nav.zip)

**Comment by thebigsleepjoe** [comment]
Func_useableladder has been historically problematic with the bots due to its different functionality than func_ladder (which is already strange enough). I will create a demo level to draft a solution and see what our options are. I appreciate your conciseness.

**Comment by thebigsleepjoe** [comment]
Do you have a script to automate navmesh creation for these types of ladders? If not, how did you apply the function you mentioned to create the nav ladder?

I'm currently using your navmesh to troubleshoot (thanks for providing that by the way), but it would be helpful to know how you did it down the road.

**Comment by Cynosphere** [comment]
It generates a ladder center to the vectors specified. I just manually took two points close to the nearest snapping point when `nav_snap_to_grid` is 2, rounded them up, subtracted the difference on the axis for the normal and divided it by two. Took the Z axis for the bottom of the ladder for the second vector's Z. Width is also the difference on the normal axis.

Sorry if my explanation isn't the greatest, its hard to formulate my method into words

**Comment by thebigsleepjoe** [comment]
Thank you for your explanation. I have made a minor adjustment to fix the issue of the characters getting stuck on these types of ladders. This solution seems to work well on the provided navmesh. However, since these ladders are a legacy form that is not well-supported by Garry's Mod, it's not a perfect solution but it's good enough for now.
