### ISSUE TITLE
[FEATURE] Jackal and Sidekick Support

### ISSUE THREAD

**Issue by Pawel99UK** [thebigsleepjoe/TTT-Bots-2#17]
## What is the new feature?
This feature is to add support for the AI to be able to use the sidekick deagle and convert enemy bots to their side.

What should happen is that either the jackal bot has a special task to look for a AI who isn't part of the large group of bots and then convert them or that there would be a special interaction of the jackal bot convincing the unsuspecting victim to follow them in which after getting in a secluded area they would turn them. To be more specific the AI who would become the sidekick might have a couple different reactions to the turning. 
Number 1: they might try to kill the Jackal. 
Number 2: They might allow the Jackal to turn them. 
Number 3: They might run away from them and put a KOS on them.

## Purpose/motivation
The purpose or motivation as why this should be implemented and why the bots should be able to use this is because the jackal and sidekick by far are the most downloaded and used roles on the workshop with over 75k downloads. Meaning that there is a massive overlap with the TTT-Bots-2 addon and jackal/sidekick addons. Which overall means that adding this quality of life addition would enhance the general gameplay of the addon and make the bots more human like which also link with [FEATURE] Refactor behavior tree. The reason of why this should be added into the addon rather to be implemented with the Refactor behavior tree is because The Jackal role is a large part of TTT2 being nearly half the downloads of the TTT2 base itself.

## Additional context
![image](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/68613257/0dd85299-5ab2-44d7-ad90-de66bd53547d)

**Comment by thebigsleepjoe** [comment]
Feature is ready in v1.1-role branch
