### ISSUE TITLE
[FEATURE] Update Maps to include traitor traps

### ISSUE THREAD

**Issue by Pawel99UK** [thebigsleepjoe/TTT-Bots-2#22]
## What is the new feature?
Adding traitor traps into the base maps built in with the addon

Adding traitor traps or a traitor room to some of the maps would make them have more replay value and could link with adding more features to the bots like giving them the ability to use traitor traps for their specific maps.

## Purpose/motivation
The purpose of why this should be added is for more replay-ability and  enjoyment on the default maps.

**Comment by thebigsleepjoe** [comment]
I understand where you are coming from and agree it would be a fantastic feature if implemented correctly. However, I fear such a feature is too complicated to undertake. The best I could do is make the traitor bots activate T-doors if they are blocked by one, but even that may pose some significant challenges.

They are not included on my bot maps for a couple of reasons. Firstly, my bot maps are supposed to be designed for bots to flourish and play without being (unintentionally) limited, as they may be on certain extant TTT maps. Secondly, if I include traitor triggers/traps on my bot maps, it may give the impression that the bots can use them.

If/when the bots can utilize them effectively, I will put them in the bot maps, but that may be some time from now.
