### ISSUE TITLE
[BUG] cannot resume dead coroutine

### ISSUE THREAD

**Issue by EntranceJew** [thebigsleepjoe/TTT-Bots-2#24]
## Game version/server type
* SERVER TYPE (PICK ONE): SRCDS
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: TTTBots version: v0.9.4 (12/18/23)

## Describe the bug
Bot AI freezes

## Stack trace/error

```
Had errors generating;  cannot resume dead coroutine
Had errors generating;  addons/ttt-bots-2/lua/tttbots2/lib/sv_pathmanager.lua:897: attempt to index local 'destination' (a nil value)
Had errors generating;  cannot resume dead coroutine
Had errors generating;  addons/ttt-bots-2/lua/tttbots2/lib/sv_pathmanager.lua:897: attempt to index local 'destination' (a nil value)
Had errors generating;  cannot resume dead coroutine
Had errors generating;  addons/ttt-bots-2/lua/tttbots2/lib/sv_pathmanager.lua:897: attempt to index local 'destination' (a nil value)
```
⚠️ If there is no error, please ensure you remove the triple backticks, or else your formatting will break.

## Reproducing the bug
1. Go to `ttt_mc_skylandv5`
2. Generate a basic navmesh
3. Bots freak out

## Expected behavior
Bots behave as usual.

## Additional context
Happens even after a map reload.

**Comment by thebigsleepjoe** [comment]
Does this happen on other maps?

**Comment by thebigsleepjoe** [comment]
Nvm I see what it is. I pushed a change that should fix it -- seems like a bug caused by a portal being improperly set up by the map creator

Please try latest, v0.9.5b

**Comment by EntranceJew** [comment]
Checked it out, they all handle it just fine now. Thanks!

**Comment by thebigsleepjoe** [comment]
No problem! Thanks for the report.
