### ISSUE TITLE
[BUG] ArcCW weapons break TTT bots

### ISSUE THREAD

**Issue by somefnfplayerlol** [thebigsleepjoe/TTT-Bots-2#27]
## Game version/server type
* SERVER TYPE (PICK ONE): P2P
* WHICH TTT (PICK ONE): TTT
* WHAT VERSION OF BOTS: v1.0.2 (12/24/23)

## Describe the bug
If a bot has a ArcCW weapon in their hands, they will send errors to the console and do nothing.

## Stack trace/error
The error, if any. Example:

```
[TTT Bots 2.0] lua/tttbots2/components/sv_inventory.lua:187: attempt to perform arithmetic on field 'Delay' (a nil value)
  1. unknown - lua/tttbots2/sh_tttbots2.lua:129
```
⚠️ If there is no error, please ensure you remove the triple backticks, or else your formatting will break.

## Reproducing the bug
1. Subscribe to the [ArcCW base](https://steamcommunity.com/workshop/filedetails/?id=2131057232)
2. Subscribe to a ArcCW gun pack (I used [Gunsmith Offensive](https://steamcommunity.com/sharedfiles/filedetails/?id=2257255110)) 
3. Have a bot pick up a ArcCW weapon (indicated by white text)

## Expected behavior
Bots should be able to fire the ArcCW weapon normally and not throw out errors and stand still.

EDIT: Like [#11](https://github.com/thebigsleepjoe/TTT-Bots-2/issues/11), but specific.

**Comment by thebigsleepjoe** [comment]
Thank you for the report. I have pushed a little hotfix for the next update, which should be coming to Steam soon. I will do further testing to make sure it is working.

**Comment by thebigsleepjoe** [comment]
Confirmed issue will be resolved on next update -- may be a couple of days until you see a difference on Steam
