### ISSUE TITLE
[BUG] New Roles Support Not Working

### ISSUE THREAD

**Issue by Pawel99UK** [thebigsleepjoe/TTT-Bots-2#30]
## Game version/server type
* SERVER TYPE (PICK ONE): P2P
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: Run the ttt_bot_version command to see the current version.
Current steam version (I dont get these errors while playing with the 1.1roles branch version of github)
## Describe the bug
The new code for the roles are not-working on the steam port.

## Stack trace/error
The error, if any. Example:
```
[TTT Bots 2.0] lua/tttbots2/components/sv_locomotor.lua:1579: attempt to index field 'DebugServer' (a nil value)
    1. unknown - lua/tttbots2/components/sv_locomotor.lua:1579
[TTT Bots 2.0] lua/tttbots2/roles/hitman.lua:6: table index is nil
    1. unknown - lua/tttbots2/roles/hitman.lua:6
        2. include - [C]:-1
            3. IncludeDirectory - lua/tttbots2/lib/sh_botlib.lua:554
                4. unknown - lua/tttbots2/lib/sv_roles.lua:141
                    5. include - [C]:-1
                        6. includeServer - lua/tttbots2/sh_tttbots2.lua:41
                            7. Reload - lua/tttbots2/sh_tttbots2.lua:92
                                8. unknown - lua/tttbots2/sh_tttbots2.lua:219
    [TTT Bots 2.0] lua/tttbots2/roles/jackal.lua:5: table index is nil
    1. unknown - lua/tttbots2/roles/jackal.lua:5
        2. include - [C]:-1
            3. IncludeDirectory - lua/tttbots2/lib/sh_botlib.lua:554
                4. unknown - lua/tttbots2/lib/sv_roles.lua:141
                    5. include - [C]:-1
                        6. includeServer - lua/tttbots2/sh_tttbots2.lua:41
                            7. Reload - lua/tttbots2/sh_tttbots2.lua:92
                                8. unknown - lua/tttbots2/sh_tttbots2.lua:219
    [TTT Bots 2.0] lua/tttbots2/roles/sidekick.lua:5: table index is nil
    1. unknown - lua/tttbots2/roles/sidekick.lua:5
        2. include - [C]:-1
            3. IncludeDirectory - lua/tttbots2/lib/sh_botlib.lua:554
                4. unknown - lua/tttbots2/lib/sv_roles.lua:141
                    5. include - [C]:-1
                        6. includeServer - lua/tttbots2/sh_tttbots2.lua:41
                            7. Reload - lua/tttbots2/sh_tttbots2.lua:92
                                8. unknown - lua/tttbots2/sh_tttbots2.lua:219
```
⚠️ If there is no error, please ensure you remove the triple backticks, or else your formatting will break.

## Reproducing the bug
1. Go to a p2p match
2. expirence the game using steam version
3. see bot code not working

## Expected behavior
The sidekick should not teamkill you. Jackal/serial killer should 1v1 at the end with any last player which only sometimes happen.

E.g., "There should not be any errors thrown," or "The bots shouldn't die after sending a chat message."

## Screenshots
Screenshots are always appreciated but not required (depending on the bug)
![image](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/68613257/86cdb985-ee08-4335-8bbf-a3ea6494e96c)
## Additional context
Providing extra context, including a mod collection or simple mod list, can hugely boost the speed at which your report gets addressed/resolved.

**Comment by thebigsleepjoe** [comment]
Resolved via commit: 
"Hotfix: Fix https://github.com/thebigsleepjoe/TTT-Bots-2/issues/30, stub out data to prevent nil index err"
