### ISSUE TITLE
[BUG] breaking entity on map causes error

### ISSUE THREAD

**Issue by EntranceJew** [thebigsleepjoe/TTT-Bots-2#32]
## Game version/server type
* SERVER TYPE (PICK ONE): SRCDS
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: v1.1-roles

## Describe the bug
Breaking a map entity causes errors.

## Stack trace/error
The error, if any. Example:

```
[TTT Bots 2.0] lua/tttbots2/components/sv_memory.lua:537: Tried to use a NULL entity!
  1. GetOwner - [C]:-1
   2. fn - lua/tttbots2/components/sv_memory.lua:537
    3. unknown - lua/ulib/shared/hook.lua:109
```
⚠️ If there is no error, please ensure you remove the triple backticks, or else your formatting will break.

## Reproducing the bug
1. Go to `ttt_batonrouge`
2. Find a radio that is playing music.
4. Break it.
5. See error

## Expected behavior
Breaking radios works normally.

**Comment by thebigsleepjoe** [comment]
This should be fixed as of v1.11-roles. I'll release it as a hotfix for the workshop ASAP as well.
