### ISSUE TITLE
[BUG] Check `minhealthdmg` on props to determine if they are breakable

### ISSUE THREAD

**Issue by Cynosphere** [thebigsleepjoe/TTT-Bots-2#33]
## Game version/server type
* SERVER TYPE: ALL
* WHICH TTT: BOTH
* WHAT VERSION OF BOTS: v1.12-roles (`6cf6ae6`)

## Describe the bug
Some maps have breakable props that aren't static but have `minhealthdmg` set extremely high to make them unbreakable. Bots will get stuck trying to break them.

The only map I know has these props is [ttt_forest_final](https://steamcommunity.com/sharedfiles/filedetails/?id=147635981)
([navmesh for convenience](https://github.com/thebigsleepjoe/TTT-Bots-2/files/13801949/ttt_forest_final.zip), most of it has the fence props avoided, but there are still some spots where they get stuck trying to break a fence)

## Stack trace/error
N/A

## Reproducing the bug
1. Play on ttt_forest_final
2. Wait for a bot to get stuck trying to break a fence

## Expected behavior
The prop's `minhealthdmg` key value is checked (`entity:GetInternalVariable("minhealthdmg")`) for either 0 or if its within the damage of the weapon.

## Screenshots

https://github.com/thebigsleepjoe/TTT-Bots-2/assets/1606710/f7350487-09b7-4c36-b320-fb3d29695691

**Comment by thebigsleepjoe** [comment]
That is unfortunate. Should be an easy fix though, I'll check it out later today or tomorrow

**Comment by thebigsleepjoe** [comment]
Pushed updated code to v1.2 dev branch, pending testing -- will close issue when completing milestone

**Comment by Cynosphere** [comment]
Tested and didn't witness any bots getting stuck

**Comment by thebigsleepjoe** [comment]
Ah, ty for testing it out. I'll close this issue out for now, then.

Appreciate the report, as always.
