### ISSUE TITLE
[BUG] retrying clients causes bots to behave strangely

### ISSUE THREAD

**Issue by EntranceJew** [thebigsleepjoe/TTT-Bots-2#34]
## Game version/server type
* SERVER TYPE (PICK ONE): SRCDS
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: v1.11-roles

## Describe the bug
Creating bots broken after forced retry.

## Stack trace/error
The error, if any. Example:

```
CreatePlayerBot: Unable to create bot [BOT] Pootis - CreateFakeClient() returned NULL.

[TTT Bots 2.0] lua/tttbots2/components/sv_locomotor.lua:52: attempt to index local 'bot' (a nil value)
  1. Initialize - lua/tttbots2/components/sv_locomotor.lua:52
   2. New - lua/tttbots2/components/sv_locomotor.lua:21
    3. CreateBot - lua/tttbots2/lib/sh_botlib.lua:829
     4. serverCallback - lua/tttbots2/commands/sh_concommands.lua:65
      5. unknown - lua/tttbots2/commands/sh_concommands.lua:50
       6. unknown - lua/includes/modules/concommand.lua:54

CreatePlayerBot: Unable to create bot [BOT] Hugh Mungus - CreateFakeClient() returned NULL.

[TTT Bots 2.0] lua/tttbots2/components/sv_locomotor.lua:52: attempt to index local 'bot' (a nil value)
  1. Initialize - lua/tttbots2/components/sv_locomotor.lua:52
   2. New - lua/tttbots2/components/sv_locomotor.lua:21
    3. CreateBot - lua/tttbots2/lib/sh_botlib.lua:829
     4. serverCallback - lua/tttbots2/commands/sh_concommands.lua:65
      5. unknown - lua/tttbots2/commands/sh_concommands.lua:50
       6. unknown - lua/includes/modules/concommand.lua:54
```

## Reproducing the bug
1. Enter a round with bots.
2. Force all clients to `retry` in console.
3. Bots will be punted from a dormant server.
4. Clients rejoin
5. Bots repopulate
6. Errors occur

## Expected behavior
No errors

**Comment by thebigsleepjoe** [comment]
That is really odd. It seems that Gmod does not have any error handling for the CreatePlayerBot function when the map/scripts are loaded but no players are connected. I noticed that the function to create a bot isn't actually visible in FP's GitHub repository. I will test this out when I get a minute.

**Comment by EntranceJew** [comment]
there's a chance that pcall / xpcall / ProtectedCall can still capture it, but i know some things don't

**Comment by thebigsleepjoe** [comment]
Made a commit to dev branch that should fix this. Pending further testing

**Comment by thebigsleepjoe** [comment]
Confirmed fixed in dev branch, pending merge to master with v1.2 milestone
