### ISSUE TITLE
[BUG] Bot-Planted C4 Cannot be Defused

### ISSUE THREAD

**Issue by Pawel99UK** [thebigsleepjoe/TTT-Bots-2#35]
## Game version/server type
* SERVER TYPE (PICK ONE): P2P
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: Run the ttt_bot_version command to see the current version.
1.2 and master
## Describe the bug
A c4 is armed but when you try to enter the menu it says you cant.
## Stack trace/error
The error, if any. Example: Silent

## Reproducing the bug
1. Play matches with bots until they plant bomb
2

## Expected behavior
The bomb should be able to be defused rather for a non-working plant menu after its planted

## Screenshots
![image](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/68613257/1020a7d0-0493-490e-ab07-63683e0425e7)

**Comment by thebigsleepjoe** [comment]
Damn. I remember having this issue on the past version, before the rework, and I thought it was fixed. Honestly this could be caused by an issue with TTT itself. I'll have to investigate this further

**Comment by thebigsleepjoe** [comment]
I played a few matches with bots and was able to successfully defuse C4 as expected. Could you include a collection or any further info I could use to troubleshoot?

**Comment by Pawel99UK** [comment]
for me it only sometimes works and i dont have any mod that should overlap

**Comment by Pawel99UK** [comment]
fixed
