### ISSUE TITLE
[BUG] inventory bug

### ISSUE THREAD

**Issue by EntranceJew** [thebigsleepjoe/TTT-Bots-2#36]
## Game version/server type
* SERVER TYPE (PICK ONE): SRCDS
* WHICH TTT (PICK ONE): TTT2
* WHAT VERSION OF BOTS: v1.13-roles (workshop)

## Stack trace/error
The error, if any. Example:

```
[TTT Bots 2.0] lua/tttbots2/components/sv_inventory.lua:187: bad argument #1 to 'ceil' (number expected, got nil)
  1. ceil - [C]:-1
   2. GetHeldWeaponInfo - lua/tttbots2/components/sv_inventory.lua:187
    3. StartCommand - lua/tttbots2/components/sv_locomotor.lua:1452
     4. fn - lua/tttbots2/sh_tttbots2.lua:139
      5. unknown - lua/ulib/shared/hook.lua:109
```

## Reproducing the bug
1. Reload the game files a few times in a live refresh.
2. Roll the dice.

## Expected behavior
This doesn't happen.

## Additional context
Hard to say what really triggers it but the latest version of TTT2 on git causes it a lot.

**Comment by thebigsleepjoe** [comment]
What is it you're live-refreshing? Is it an SWEP?

**Comment by thebigsleepjoe** [comment]
Can you test again on the latest update to the steam branch?
