### ISSUE TITLE
[FEATURE] BodyGuard Support

### ISSUE THREAD

**Issue by thewarkid** [thebigsleepjoe/TTT-Bots-2#37]
## _What is the new feature?_ 
 
_What should happen as a result of Adding built-in support for the **Bodyguard** role?_: It would allow for someone to Bodyguard a bot, or vice versa, and not have to worry about being RDM'd by their target or killed by their target if they're a traitor.

## Purpose/motivation
_What is the purpose of this request? *Why* should it behave this way? What is the reason for your suggestion?:_ Bodyguard Role adds a role that gives a guaranteed cooperative experience between two people. With bots, while you no longer have the person-to-person aspect, it can be fun to have backup or be fun to try and back up a bot in whatever they do.

## How would you add this feature? (optional)
Probably something simple as just saying "If the Bodyguard is assigned to X, and X is a bot, make sure X (And any potential teammates) also sees the Guard as a teammate." Probably something as simple as checking what team the Bodyguard is on, since TTT2 does recognize a Guard assisting a traitor as being on the traitor team.

**Comment by thebigsleepjoe** [comment]
Will totally do this. Straightforward role and won't require me to change much.
