### ISSUE TITLE
[BUG] Broken Spawn Points

### ISSUE THREAD

**Issue by McAidenvL** [thebigsleepjoe/TTT-Bots-2#38]
## Game version/server type
* SERVER TYPE: ALL
* WHICH TTT: BOTH
* WHAT VERSION OF BOTS: V1.2

## Describe the bug
Certain spawn points on ttt_bots_v5 are bugged causing who ever spawns there to remain stuck for the whole round.

## Stack trace/error
No console error

## Reproducing the bug
1. Start a round on ttt_bots_v5
2. Play until you spawn stuck/unable to move or see a bot who is stuck

## Expected behavior

When a player or bot spawns on the map they shouldn't be stuck.

## Screenshots

![20240211022211_1](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/159696149/9a7c6b30-7274-44ba-ad82-c297166f09c5)
![20240211024749_1](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/159696149/dc329b46-2968-4184-9bdf-4eea9fccccde)
![20240211025613_1](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/159696149/d9888d4a-e4ba-45c0-8653-35b2d0b408f2)

## Additional context
The Trouble in Terrorist Town Bots addon is the only one enabled. There are more spawns that are bugged but I only have these three screenshots.

**Comment by thebigsleepjoe** [comment]
I just noticed this, too. That's so weird, because I remember those spawns working just fine for the past few months. Either way, I'm pushing a commit/update to the Steam branch to fix this now. Apologies for any trouble this may have caused.
