### ISSUE TITLE
[Bug]: Bots can open/close locked doors

### ISSUE THREAD

**Issue by Will7029** [thebigsleepjoe/TTT-Bots-2#64]
### Server hosting type

ALL

### TTT Type

TTT2

### Version of Bots

1.3.2

### Describe the bug

Bots can open and close locked doors in any map which can't normally be opened or closed. This bug appeared after door fix. https://github.com/thebigsleepjoe/TTT-Bots-2/issues/60

This bug can be easly be seen from ttt_summit
https://steamcommunity.com/sharedfiles/filedetails/?id=344953351
Here is the navmesh for this map
[ttt_summit.zip](https://github.com/user-attachments/files/17538631/ttt_summit.zip)

### Stack trace/error

```shell
None
```

### Reproducing the bug

1. Open ttt_summit map with my navmesh
2. Go to meeting room and see bots open and close locked doors.

### Expected behavior

Locked doors should not be opened or closed as players normally can't interact them

### Screenshots

![door_bug](https://github.com/user-attachments/assets/f252b630-b591-438b-89da-e592db2f04d9)

**Comment by thebigsleepjoe** [comment]
Gah, I should've seen this coming because of #60.

The fix should be relatively easy, at least. I'll publish a patch when I can

**Comment by Will7029** [comment]
Hello!

I'm using version 1.3.3 and this still happens.
I tested in listen and dedicated server in TTT2. Maps ttt_summit and ttt_halflife.
TTT2 version is v0.14.0b.
![bug](https://github.com/user-attachments/assets/f1ac5a1f-76a5-4d49-9f89-ddff104393f8)

**Comment by thebigsleepjoe** [comment]
I see. I thought this issue was for locked doors--though that was a valid bug that needed to be fixed.

This is actually a more specific case. I'm putting out a patch that appears to fix the issue at least on ttt_summit. For some reason the mapper made these literal doors that you can't +use... they should've just been brushes! Expect a fix out shortly.
