### ISSUE TITLE
[BUG] Custom roles do not target each other

### ISSUE THREAD

**Issue by Pawel99UK** [thebigsleepjoe/TTT-Bots-2#8]
**Describe the bug**
Add on roles which are not part of the innocent and traitor team will co-operate with the traitors and will not fight each-other stopping the round from progressing as its a never ending stalemate. This also affects the ai by having neutral killers follow traitor plans like gather.d

**Stack trace/error**
There does not seem to be a error for this issue when it occurs.

**To Reproduce**
1. Go on and start a normal match
2. Play a couple of matches until traitors and neutral killer/s are also only alive e.g Jackal or Serial killer
3. See as the ai walk past each other and refuse to fight stalling the round until either the person uses sv_cheats to kill them or forces a round restart

**Expected behavior**
What most likely should happen is that both the enemy AI teams should fight and murder each other or they might team up until they are the last ones left alive.

**Screenshots**
![Teaming bug](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/68613257/8f5ca4c1-260e-4db4-b029-19d50f3d93ca)
![image](https://github.com/thebigsleepjoe/TTT-Bots-2/assets/68613257/3547916e-5b1e-4bae-99ba-b3064e4ee205)

**Additional context**
This Bug doesn't seem to affect No-team roles like medic or amnesiac which side with the innocents.

I hope this helps to improve the mod

**Comment by thebigsleepjoe** [comment]
Oh boy, I already know this issue is going to be challenging. It will require me to rebuild the targeting system, but I have a few ideas on how. I'll see what I can do.

**Comment by thebigsleepjoe** [comment]
Issue will be fixed upon next update (v1.1-roles)
